language: node_js
node_js:
  - "10"
dist: trusty

cache: npm

sudo: false

services:
  - postgresql

install:
  - npm install

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli
  - psql -c "CREATE DATABASE db;" -U postgres
  - psql -c "CREATE USER dbms WITH PASSWORD 'password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE db TO dbms;" -U postgres

script:
  - ng lint

